use_frameworks!

platform :ios, '10.0'

target 'Live2D_Example' do
  pod 'Live2D', :path => '../'

  target 'Live2D_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
